### ISSUE TITLE
Dataset for Fake Notes

### ISSUE THREAD

**Issue by nareshr8** [hritik25/DRDO-Fake-Currency-Identification#1]
Can you share the URL from where did you get the dataset for Fake Notes.

**Comment by saipriya-ar** [comment]
yes can you share the dataset sir 
to this mail arsaipriyakrishna2011@gmail.com
thanks in advance

**Comment by SukhnandanMalhotra** [comment]
@hritik25 Could you please share the data set for fake currency, kindly mail it to sukh.malhotra@gmail.com
Thanks

**Comment by niharika-98** [comment]
@hritik25 can you share the data set for fake currency sir, kindly mail it to sschakravarthi@ieee.org
Thanks

**Comment by rohinisamanvitha** [comment]
Can you share the dataset.Please mail me at rohinisamanvithavarre98@gmail.com

**Comment by alzuabi** [comment]
could you please share dataset.Please mail me at [alzuabi.ibr@gmail.com](mailto:alzuabi.ibr@gmail.com)
Thanks.

**Comment by arjunmohnot** [comment]
Hello if possible please share the dataset for the fake currency I'm making the tflite model to run this on android phones.
Regards,
Arjun Mohnot
am2027@bennett.edu.in

**Comment by rohinisamanvitha** [comment]
I didn't receive the dataset. Sorry

**Comment by sim12cool** [comment]
I am making a final year project on the topic "fake currency detection",kindly mail the dataset sir for the same on simran.gupta.1202@gmail.com .Would be a great help!Thanks.

**Comment by rohinisamanvitha** [comment]
I didn't receive the dataset sorry

**Comment by hritik25** [comment]
Hi, I actually created the dataset myself, by clicking pictures of the currency notes. The project work also required permission from the DRDO for using the currency note pictures.

**Comment by sim12cool** [comment]
Okay .

**Comment by gokulct** [comment]
Sir can you please mail the dataset to gokulcthankappan@gmail.com. i am doing my final year project.
Thank you
